services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    env_file:
      - ../.env
    environment:
      - PUID=${GLOBAL_PUID}
      - PGID=${GLOBAL_PGID}
      - TZ=Etc/UTC
    volumes:
      - ./config:/config
      - /mnt/data:/data
    ports:
      - 7878:7878
    restart: unless-stopped
