http:
  port: 80
  internalUrl: "http://filebrowser:80"

server:
  sources:
    - path: "/folder"
      name: "Nube"

auth:
  adminUsername: admin
  adminPassword: $PASSWORD
  methods:
    password:
      enabled: true

integrations:
  office:
    url: "https://your.domain.com" #domain or ip
    internalUrl: "http://onlyoffice:80"
    secret: "YOUR-SECRET-KEY"
