services:
  syncthing:
    image: syncthing/syncthing
    container_name: syncthing
    hostname: homelab
    environment:
      - PUID=${GLOBAL_PUID}
      - PGID=${GLOBAL_PGID}
    volumes:
      - /mnt/data:/var/syncthing
    network_mode: host
    restart: unless-stopped
