[proxmox_host]
pve         ansible_host=192.168.10.2

[lxc_mgmt]
devops      ansible_host=192.168.10.11

[lxc_network]
adguard     ansible_host=192.168.10.3
nginx_proxy ansible_host=192.168.10.4
tailscale   ansible_host=192.168.10.5
cloudflare  ansible_host=192.168.10.6

[lxc_monitoring]
monitor     ansible_host=192.168.10.10

[lxc_media]
arrsuite    ansible_host=192.168.10.20
frontend    ansible_host=192.168.10.21
immich      ansible_host=192.168.10.22

[lxc_apps]
vaultwarden ansible_host=192.168.10.23
radicale    ansible_host=192.168.10.24
cloud       ansible_host=192.168.10.25

[lxc_ai]
llm         ansible_host=192.168.10.26

[lxc:children]
lxc_mgmt
lxc_network
lxc_monitoring
lxc_media
lxc_apps
lxc_ai

