[global]
    server string = samba
    idmap config * : range = 3000-7999
    security = user
    server min protocol = SMB2

    load printers = no
    printing = bsd
    printcap name = /dev/null
    disable spoolss = yes

    host msdfs = no
    wide links = yes
    follow symlinks = yes
    unix extensions = no
    acl allow execute always = yes
    ea support = yes

    vfs objects = catia fruit streams_xattr
    fruit:resource = file
    fruit:metadata = stream
    fruit:locking = netatalk
    fruit:encoding = native
    fruit:model = TimeCapsule
    fruit:aapl = yes
    fruit:time machine = yes

    mangled names = no
    dos charset = CP850
    unix charset = UTF-8

[NAS]
    path = /storage
    comment = NAS
    browseable = yes
    writable = yes
    read only = no
    valid users = admin
    force user = admin
    force group = smb
    create mask = 0664
    directory mask = 0775

[LLM]
    path = /llm_storage
    comment = LLM
    browseable = yes
    writable = yes
    read only = no
    valid users = llm
    force user = llm
    force group = smb
    create mask = 0664
    directory mask = 0775
