services:
  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - /opt/docker/calibre/data:/config
      - /mnt/data/comics/calibre:/libros
    ports:
      - "8082:8080"
      - "8081:8081"
    networks:
      - soulsync-network
    restart: unless-stopped

networks:
  soulsync-network:
    external: true
