services:
  syncthing:
    image: syncthing/syncthing
    container_name: syncthing
    hostname: homelab
    environment:
      - PUID=0
      - PGID=0
    volumes:
      - ./config:/var/syncthing
      - $SYNC_MOUNT:/mnt/data
    network_mode: host
    restart: unless-stopped
